language: node_js
node_js:
  - "12.16.3"

branches:
  only:
    - develop

before_script:
  - npm install -g firebase-tools
  - npm install -g preact-cli
  - npm install

script:
  -

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
