language: node_js
node_js:
  - "12.16.3"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - firebase deploy --only hosting:bantay-bayan --token $FIREBASE_TOKEN
